;;; zr-czkawka-test.el --- Tests for zr-czkawka -*- lexical-binding: t; -*-

;;; Commentary:

;; ERT test suite for zr-czkawka: CLI runner, JSON parser, Virtual Dired
;; rendering, duplicate flagging, and integration.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'dired)
(require 'dired-x)
(require 'subr-x)

(load (expand-file-name
       "../zr-czkawka.el"
       (file-name-directory (or load-file-name buffer-file-name)))
      nil 'nomessage)

(ert-deftest zr-czkawka-test-parse-json-hash ()
  "Test parsing czkawka HASH mode JSON output."
  (let* ((json-str "{\"42\":[[{\"path\":\"/tmp/dir1/c.txt\",\"modified_date\":100,\"size\":42,\"hash\":\"hash1\"},{\"path\":\"/tmp/dir2/d.txt\",\"modified_date\":200,\"size\":42,\"hash\":\"hash1\"}]],\"46\":[[{\"path\":\"/tmp/dir1/a.txt\",\"modified_date\":150,\"size\":46,\"hash\":\"hash2\"},{\"path\":\"/tmp/dir2/b.txt\",\"modified_date\":250,\"size\":46,\"hash\":\"hash2\"}]]}")
         (parsed (json-parse-string json-str :object-type 'alist :array-type 'list))
         (groups (zr-czkawka-dup--parse-json parsed)))
    (should (= (length groups) 2))
    (let ((g1 (nth 0 groups))
          (g2 (nth 1 groups)))
      (should (= (alist-get 'id g1) 1))
      (should (= (alist-get 'size g1) 42))
      (should (string= (alist-get 'hash g1) "hash1"))
      (should (= (length (alist-get 'files g1)) 2))
      (should (= (alist-get 'id g2) 2))
      (should (= (alist-get 'size g2) 46))
      (should (string= (alist-get 'hash g2) "hash2")))))

(ert-deftest zr-czkawka-test-parse-json-size-and-name ()
  "Test parsing czkawka SIZE and NAME mode JSON output."
  ;; SIZE mode
  (let* ((size-json "{\"100\":[{\"path\":\"/tmp/f1\",\"size\":100,\"modified_date\":1,\"hash\":\"\"},{\"path\":\"/tmp/f2\",\"size\":100,\"modified_date\":2,\"hash\":\"\"}]}")
         (parsed (json-parse-string size-json :object-type 'alist :array-type 'list))
         (groups (zr-czkawka-dup--parse-json parsed)))
    (should (= (length groups) 1))
    (let ((g (car groups)))
      (should (= (alist-get 'size g) 100))
      (should (null (alist-get 'hash g)))
      (should (= (length (alist-get 'files g)) 2))))
  ;; NAME mode
  (let* ((name-json "{\"dup.txt\":[{\"path\":\"/tmp/dir1/dup.txt\",\"size\":50,\"modified_date\":1,\"hash\":\"\"},{\"path\":\"/tmp/dir2/dup.txt\",\"size\":80,\"modified_date\":2,\"hash\":\"\"}]}")
         (parsed (json-parse-string name-json :object-type 'alist :array-type 'list))
         (groups (zr-czkawka-dup--parse-json parsed)))
    (should (= (length groups) 1))
    (let ((g (car groups)))
      (should (string= (alist-get 'key g) "dup.txt"))
      (should (= (length (alist-get 'files g)) 2)))))

(ert-deftest zr-czkawka-test-build-args ()
  "Test CLI arguments builder for czkawka dup."
  (let* ((zr-czkawka-dup-min-file-size 1024)
         (zr-czkawka-dup-hash-type "BLAKE3")
         (args (zr-czkawka-dup--build-args '("/tmp/dir1" "/tmp/dir2") "HASH")))
    (should (equal args (list "-d" (expand-file-name "/tmp/dir1")
                              "-d" (expand-file-name "/tmp/dir2")
                              "-s" "hash"
                              "-m" "1024"
                              "-t" "blake3")))))

(ert-deftest zr-czkawka-test-render-buffer-and-navigation ()
  "Test buffer rendering, dired-subdir-alist, and navigation."
  (let* ((tmp-dir (make-temp-file "zr-czkawka-test-render" t))
         (sub1 (expand-file-name "sub1" tmp-dir))
         (sub2 (expand-file-name "sub2" tmp-dir))
         (f1 (expand-file-name "a.txt" sub1))
         (f2 (expand-file-name "b.txt" sub2))
         (f3 (expand-file-name "c.txt" sub1))
         (f4 (expand-file-name "d.txt" sub2))
         (buf-name "*test-zr-czkawka-render*"))
    (make-directory sub1 t)
    (make-directory sub2 t)
    (with-temp-file f1 (insert "group 1 content"))
    (with-temp-file f2 (insert "group 1 content"))
    (with-temp-file f3 (insert "group 2 content here"))
    (with-temp-file f4 (insert "group 2 content here"))
    (unwind-protect
        (let* ((groups `(((id . 1)
                          (key . "15")
                          (size . 15)
                          (hash . "hash12345678")
                          (files . (((path . ,f1) (modified_date . 100))
                                    ((path . ,f2) (modified_date . 200)))))
                         ((id . 2)
                          (key . "20")
                          (size . 20)
                          (hash . "hash87654321")
                          (files . (((path . ,f3) (modified_date . 300))
                                    ((path . ,f4) (modified_date . 150)))))))
               (params (list :directories (list tmp-dir)
                             :search-method "HASH"
                             :buffer-name buf-name)))
          (zr-czkawka-dup--render-buffer groups params)
          (with-current-buffer (get-buffer buf-name)
            (should zr-czkawka-dup-mode)
            (should (= (length dired-subdir-alist) 2))
            (should (string-prefix-p " Czkawka Dup: 2 groups" header-line-format))
            (goto-char (point-min))
            (dired-next-line 1)
            (should (string= (dired-get-filename) f1))
            (dired-next-subdir 1)
            (dired-next-line 1)
            (should (string= (dired-get-filename) f3))))
      (when (get-buffer buf-name)
        (kill-buffer buf-name))
      (delete-directory tmp-dir t))))

(ert-deftest zr-czkawka-test-flag-duplicates ()
  "Test flagging duplicates: keep newest, keep oldest, and keep first."
  (let* ((tmp-dir (make-temp-file "zr-czkawka-test-flag" t))
         (f1 (expand-file-name "1.txt" tmp-dir))
         (f2 (expand-file-name "2.txt" tmp-dir))
         (f3 (expand-file-name "3.txt" tmp-dir))
         (buf-name "*test-zr-czkawka-flag*"))
    (with-temp-file f1 (insert "dup"))
    (with-temp-file f2 (insert "dup"))
    (with-temp-file f3 (insert "dup"))
    (unwind-protect
        (let* ((groups `(((id . 1)
                          (size . 3)
                          (hash . "h")
                          (files . (((path . ,f1) (modified_date . 100))
                                    ((path . ,f2) (modified_date . 300))
                                    ((path . ,f3) (modified_date . 200)))))))
               (params (list :directories (list tmp-dir) :buffer-name buf-name)))
          (zr-czkawka-dup--render-buffer groups params)
          (with-current-buffer (get-buffer buf-name)
            ;; Test keep newest: f2 is newest (mtime 300), f1 and f3 should be flagged
            (zr-czkawka-dup-flag-all-except-newest)
            (let ((dired-marker-char dired-del-marker))
              (should (equal (sort (dired-get-marked-files) #'string<)
                             (sort (list f1 f3) #'string<))))
            ;; Unmark all
            (dired-unmark-all-marks)
            ;; Test keep oldest: f1 is oldest (mtime 100), f2 and f3 should be flagged
            (zr-czkawka-dup-flag-all-except-oldest)
            (let ((dired-marker-char dired-del-marker))
              (should (equal (sort (dired-get-marked-files) #'string<)
                             (sort (list f2 f3) #'string<))))
            ;; Unmark all
            (dired-unmark-all-marks)
            ;; Test keep first: f1 is first, f2 and f3 should be flagged
            (zr-czkawka-dup-flag-all-except-first)
            (let ((dired-marker-char dired-del-marker))
              (should (equal (sort (dired-get-marked-files) #'string<)
                             (sort (list f2 f3) #'string<))))))
      (when (get-buffer buf-name)
        (kill-buffer buf-name))
      (delete-directory tmp-dir t))))

(ert-deftest zr-czkawka-test-cli-integration ()
  "Integration test running czkawka_cli binary on test files."
  (skip-unless (or (executable-find zr-czkawka-program)
                   (file-executable-p zr-czkawka-program)))
  (let* ((tmp-dir (make-temp-file "zr-czkawka-integ" t))
         (d1 (expand-file-name "dir1" tmp-dir))
         (d2 (expand-file-name "dir2" tmp-dir))
         (f1 (expand-file-name "file1.txt" d1))
         (f2 (expand-file-name "file2.txt" d2))
         (content "unique content for integration testing duplicate files 1234567890")
         (buf-name "*test-zr-czkawka-integ*")
         (done nil)
         (result-groups nil))
    (make-directory d1 t)
    (make-directory d2 t)
    (with-temp-file f1 (insert content))
    (with-temp-file f2 (insert content))
    (unwind-protect
        (let ((args (list "dup" "-d" tmp-dir "-m" "1" "-s" "hash")))
          (zr-czkawka-run
           args
           (lambda (data)
             (setq result-groups (zr-czkawka-dup--parse-json data))
             (zr-czkawka-dup--render-buffer result-groups
                                            (list :directories (list tmp-dir)
                                                  :buffer-name buf-name))
             (setq done t)))
          (while (not done)
            (accept-process-output nil 0.1))
          (should (= (length result-groups) 1))
          (let ((grp (car result-groups)))
            (should (= (length (alist-get 'files grp)) 2)))
          (with-current-buffer (get-buffer buf-name)
            (should (= (length dired-subdir-alist) 1))
            (goto-char (point-min))
            (dired-next-line 1)
            (should (member (dired-get-filename) (list f1 f2)))))
      (when (get-buffer buf-name)
        (kill-buffer buf-name))
      (delete-directory tmp-dir t))))

(ert-deftest zr-czkawka-test-flag-current-group-only ()
  "Test flagging duplicates only within the current group."
  (let* ((tmp-dir (make-temp-file "zr-czkawka-test-grp" t))
         (f1 (expand-file-name "1.txt" tmp-dir))
         (f2 (expand-file-name "2.txt" tmp-dir))
         (f3 (expand-file-name "3.txt" tmp-dir))
         (f4 (expand-file-name "4.txt" tmp-dir))
         (buf-name "*test-zr-czkawka-grp*"))
    (with-temp-file f1 (insert "dup1"))
    (with-temp-file f2 (insert "dup1"))
    (with-temp-file f3 (insert "dup2"))
    (with-temp-file f4 (insert "dup2"))
    (unwind-protect
        (let* ((groups `(((id . 1)
                          (size . 4)
                          (files . (((path . ,f1) (modified_date . 200))
                                    ((path . ,f2) (modified_date . 100)))))
                         ((id . 2)
                          (size . 4)
                          (files . (((path . ,f3) (modified_date . 200))
                                    ((path . ,f4) (modified_date . 100)))))))
               (params (list :directories (list tmp-dir) :buffer-name buf-name)))
          (zr-czkawka-dup--render-buffer groups params)
          (with-current-buffer (get-buffer buf-name)
            ;; Point is on f1 (Group 1)
            (goto-char (point-min))
            (dired-next-line 1)
            (should (string= (dired-get-filename) f1))
            ;; Flag current group only (prefix arg = t)
            (zr-czkawka-dup-flag-all-except-newest t)
            (let ((dired-marker-char dired-del-marker))
              ;; Only f2 should be flagged; f4 in group 2 should NOT be flagged
              (should (equal (dired-get-marked-files) (list f2))))))
      (when (get-buffer buf-name)
        (kill-buffer buf-name))
      (delete-directory tmp-dir t))))

(ert-deftest zr-czkawka-test-diff ()
  "Test diff command invoking diff on counterpart file."
  (let* ((tmp-dir (make-temp-file "zr-czkawka-test-diff" t))
         (f1 (expand-file-name "a.txt" tmp-dir))
         (f2 (expand-file-name "b.txt" tmp-dir))
         (buf-name "*test-zr-czkawka-diff*")
         (diff-called nil))
    (with-temp-file f1 (insert "diff test"))
    (with-temp-file f2 (insert "diff test"))
    (unwind-protect
        (let* ((groups `(((id . 1)
                          (size . 9)
                          (files . (((path . ,f1) (modified_date . 100))
                                    ((path . ,f2) (modified_date . 200)))))))
               (params (list :directories (list tmp-dir) :buffer-name buf-name)))
          (zr-czkawka-dup--render-buffer groups params)
          (with-current-buffer (get-buffer buf-name)
            (goto-char (point-min))
            (dired-next-line 1)
            (cl-letf (((symbol-function 'diff)
                       (lambda (file-a file-b &rest _)
                         (setq diff-called (list file-a file-b))))
                      ((symbol-function 'display-graphic-p) (lambda () nil)))
              (zr-czkawka-dup-diff)
              (should (equal diff-called (list f1 f2))))))
      (when (get-buffer buf-name)
        (kill-buffer buf-name))
      (delete-directory tmp-dir t))))

(ert-deftest zr-czkawka-test-keymap ()
  "Test key bindings in `zr-czkawka-dup-mode-map'."
  (should (eq (lookup-key zr-czkawka-dup-mode-map (kbd "% n")) #'zr-czkawka-dup-flag-all-except-newest))
  (should (eq (lookup-key zr-czkawka-dup-mode-map (kbd "% o")) #'zr-czkawka-dup-flag-all-except-oldest))
  (should (eq (lookup-key zr-czkawka-dup-mode-map (kbd "% f")) #'zr-czkawka-dup-flag-all-except-first)))

(provide 'zr-czkawka-test)

;;; zr-czkawka-test.el ends here
