;;; zr-org-link-test.el --- Tests for zr-org-link -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'zr-org-link)
(require 'zr-test-helpers)

(ert-deftest zr-org-link-test-ssh-opens-once ()
  (dolist (text '("https://example.com/path?q=1&x=2\n"
                  "[[http://example.com/path][Example]]\n"))
    (dolist (environment '(("SSH_CONNECTION" frame)
                           ("SSH_CLIENT" frame)
                           ("SSH_CONNECTION" process)
                           ("SSH_CLIENT" process)))
      (zr-test-with-org-buffer text
        (search-forward "example")
        (let ((org-open-at-point-functions '(zr-org-link-open-at-point))
              sent)
          (cl-letf (((symbol-function 'getenv)
                     (lambda (variable &optional frame)
                       (when (and (equal variable (car environment))
                                  (eq (if frame 'frame 'process)
                                      (cadr environment)))
                         "ssh-session")))
                    ((symbol-function 'zr-wezterm-send-json)
                     (lambda (payload)
                       (push payload sent)
                       nil))
                    ((symbol-function 'browse-url)
                     (lambda (&rest _) (ert-fail "Unexpected browser fallback"))))
            (let ((url (org-element-property :raw-link (org-element-context))))
              (should (zr-org-link-open-at-point))
              (should (equal sent `(((type . "open_uri") (uri . ,url))))))
            (setq sent nil)
            (org-open-at-point)
            (should (= (length sent) 1))))))))

(ert-deftest zr-org-link-test-ignores-local-and-non-http-links ()
  (dolist (case '((nil "https://example.com/\n")
                  ("ssh-session" "[[file:/tmp/example.txt]]\n")
                  ("ssh-session" "Plain text\n")))
    (zr-test-with-org-buffer (cadr case)
      (cl-letf (((symbol-function 'getenv) (lambda (&rest _) (car case)))
                ((symbol-function 'zr-wezterm-send-json)
                 (lambda (&rest _) (ert-fail "Unexpected WezTerm request"))))
        (should-not (zr-org-link-open-at-point))))))

(ert-deftest zr-org-link-test-link-escapes-html ()
  (let ((html (zr-org-link--export "a&b" "<label>" 'html nil)))
    (should (string-match-p "&lt;label&gt;" html))
    (should (string-match-p "a%26b" html))
    (should-not (string-match-p ">\(<label>\)" html))))

(ert-deftest zr-org-link-test-link-handler-restoration ()
  (let ((org-link-parameters (copy-tree org-link-parameters)))
    (org-link-set-parameters "dict" :follow #'ignore)
    (zr-org-link-mode 1)
    (zr-org-link-mode 1)
    (zr-org-link-mode -1)
    (should (eq (org-link-get-parameter "dict" :follow) #'ignore))))

(provide 'zr-org-link-test)
;;; zr-org-link-test.el ends here
